[build]
  base = "lvtv-website"      # Ensure this directory exists
  publish = "lvtv-website/dist"  # Ensure this directory is the correct build output
  command = "npm run build"  # The build command to compile your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

